version: '3.8'

services:
  imc-app:
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production